config/routes.rb
Rails.application.routes.draw do
  resources :residents

end

app/models/resident.rb
class Resident < ActiveRecord::Base
	:has_many Job
	:has_one Residence
	:has_many_through 

	def eligible 
		true
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/residents_controller.rb
class ResidentsController < ApplicationController
  before_action :set_resident, only: [:show, :edit, :update, :destroy]

  # GET /residents
  # GET /residents.json
  def index
    @residents = Resident.all
  end

  # GET /residents/1
  # GET /residents/1.json
  def show
  end

  # GET /residents/new
  def new
    @resident = Resident.new
  end

  # GET /residents/1/edit
  def edit
  end

  # POST /residents
  # POST /residents.json
  def create
    @resident = Resident.new(resident_params)

    respond_to do |format|
      if @resident.save
        format.html { redirect_to @resident, notice: 'Resident was successfully created.' }
        format.json { render :show, status: :created, location: @resident }
      else
        format.html { render :new }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residents/1
  # PATCH/PUT /residents/1.json
  def update
    respond_to do |format|
      if @resident.update(resident_params)
        format.html { redirect_to @resident, notice: 'Resident was successfully updated.' }
        format.json { render :show, status: :ok, location: @resident }
      else
        format.html { render :edit }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residents/1
  # DELETE /residents/1.json
  def destroy
    @resident.destroy
    respond_to do |format|
      format.html { redirect_to residents_url, notice: 'Resident was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resident
      @resident = Resident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resident_params
      params.require(:resident).permit(:first_name, :last_name, :birth, :arrival, :asylum_status, :work_permit, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bella</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/residents/_form.html.erb
<%= form_for(@resident) do |f| %>
  <% if @resident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resident.errors.count, "error") %> prohibited this resident from being saved:</h2>

      <ul>
      <% @resident.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :birth %><br>
    <%= f.datetime_select :birth, :start_year => 1900 %>
  </div>
  <div class="field">
    <%= f.label :arrival %><br>
    <%= f.datetime_select :arrival %>
  </div>
  <div class="field">
    <%= f.label :asylum_status %><br>
    <%= f.number_field :asylum_status %>
  </div>
  <div class="field">
    <%= f.label :work_permit %><br>
    <%= f.number_field :work_permit %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/residents/edit.html.erb
<h1>Editing Resident</h1>

<%= render 'form' %>

<%= link_to 'Show', @resident %> |
<%= link_to 'Back', residents_path %>

app/views/residents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Residents</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Birth</th>
      <th>Arrival</th>
      <th>Asylum status</th>
      <th>Work permit</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @residents.each do |resident| %>
      <tr>
        <td><%= resident.first_name %></td>
        <td><%= resident.last_name %></td>
        <td><%= resident.birth %></td>
        <td><%= resident.arrival %></td>
        <td><%= resident.asylum_status %></td>
        <td><%= resident.work_permit %></td>
        <td><%= resident.country %></td>
        <td><%= link_to 'Show', resident %></td>
        <td><%= link_to 'Edit', edit_resident_path(resident) %></td>
        <td><%= link_to 'Destroy', resident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resident', new_resident_path %>

app/views/residents/new.html.erb
<h1>New Resident</h1>

<%= render 'form' %>

<%= link_to 'Back', residents_path %>

app/views/residents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @resident.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @resident.last_name %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @resident.birth %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @resident.arrival %>
</p>

<p>
  <strong>Asylum status:</strong>
  <%= @resident.asylum_status %>
</p>

<p>
  <strong>Work permit:</strong>
  <%= @resident.work_permit %>
</p>

<p>
  <strong>Country:</strong>
  <%= @resident.country %>
</p>

<p>
  <strong>Eligible:</strong>
  <%= @resident.eligible %>
</p>

<%= link_to 'Edit', edit_resident_path(@resident) %> |
<%= link_to 'Back', residents_path %>